version: "3"
services:
  client:
   build: ./client
   ports:
    -  3000:3000
   container_name: naruhodo-client
   networks:
    -  frontend
   depends_on:
    - server
   stdin_open: true
   tty: true

  server:
   build: ./server
   ports:
     - 3001:3001
   container_name: naruhodo-server
   networks:
     - frontend
     - backend

   depends_on:
    - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

networks:
  frontend:
  backend:

volumes:
  mongo-data:
    driver: local